"""empty message

Revision ID: 30ab50c4cd48
Revises: e776db59335f
Create Date: 2020-06-25 09:26:17.575536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ab50c4cd48'
down_revision = 'e776db59335f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Movie','releasedate',
                existing_type=sa.VARCHAR())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
